AllCops:
  TargetRubyVersion: 2.7.8

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Exclude:
    - "test/**/*"
